---
format:
  revealjs:
    logo: "https://cms-cdn.lmu.de/assets/img/Logo_LMU.svg"
    footer: "Digitale Datenspuren - JoFo/Wisskomm DGPuK 2023 - Valerie Hase"
    center-title-slide: false
    theme: ["theme/q-theme.scss"]
    code-fold: show
    code-copy: true
    self-contained: true
    number-sections: false
    smaller: true
    highlight-style: atom-one
    preview-links: auto
    progress: true
execute:
  echo: true
bibliography: "references/references.bib"
csl: references/apa.csl
---

<h1>Digitale Datenspuren nutzbar machen</h1>

<h3>Datenspenden als Methode der Kommunikationswissenschaft</h3>

<hr>

Sitzung 1️⃣: Begrüßung

Valerie Hase (Ludwig-Maximilians-Universität München)

`r fontawesome::fa("github", "black")` [github.com/valeriehase](https://github.com/valeriehase)

`r fontawesome::fa("globe", "black")` [valerie-hase.com](https://valerie-hase.com/)

## Wer seid ihr?

Bitte die Hand heben 🤚, wenn ihr ....

::: incremental
-   von digitalen Datenspuren als Begriff bereits gehört habt
-   mit APIs gearbeitet habt
-   mit Datenspenden gearbeitet habt
-   mit automatisierter Inhaltsanalyse gearbeitet habt
-   R regelmäßig nutzt
-   andere Programmiersprachen (z. B. Python) regelmäßig nutzt
:::

## Wer bin ich?

-   Akademische Rätin a. Z., LMU München (vorher: Universität Zürich, LSE, WWU Münster)

-   Fokus:

    -   CSS (automatisierte Inhaltsanalyse & digitale Datenspuren)
    -   Digitaler Journalismus
    -   Krisenkommunikation

-   Mehr Infos:

    -   `r fontawesome::fa("github", "black")` [github.com/valeriehase](https://github.com/valeriehase)

    -   `r fontawesome::fa("globe", "black")` [valerie-hase.com](https://valerie-hase.com/)

## Vielen Dank für die Organisation 🙌

Shoutout an: [Mittelbaunetzwerk Journalismusforschung](https://mijofo.wordpress.com/) & [Mittelbaunetzwerk Wissenschaftskommunikation](https://www.dgpuk.de/de/wissenschaftskommunikation.html)

-   Janine N. Blessing
-   Lea Sophia Lehner
-   Michael Graßl
-   Nils Bienzeisler
-   Nina Fabiola Schumacher
-   Vera Katzenberger

## Worum geht es heute?

::: incremental
-   ✅ Digitale Datenspuren als *Typ* von Daten verstehen
-   ✅ Datenspende als *Methode* des Datenzugangs verstehen
-   ✅ Überblick schaffen (Entscheidungen; Vor- & Nachteile)
-   ❌ Detailierte Implementierung (z.B. Datenspende-Tools)
:::

## Ablauf

|                |                                                           |     |
|-----------------|--------------------------------------|-----------------|
| Uhrzeit ⏰     |                                                           |     |
| 11:00 -- 11:10 | 1️⃣ Begrüßung                                              |     |
| 11:10 -- 12:00 | 2️⃣ Einführung: digitale Datenspuren & Datenspenden        |     |
| 12:00 -- 12:15 | Kaffeepause ☕                                            |     |
| 12:15 -- 13:15 | 3️⃣ Datenspenden in der Praxis: Forschungsdesign & Analyse |     |
| 13:15 -- 13:30 | 4️⃣ Wrap-Up                                                |     |

## R Packages

Wer in Session 3️⃣ in R mitmachen möchte, kann sich gerne vorab folgende Pakete herunterladen:

```{r, eval = FALSE}
install.packages(c("tidyverse",
                   "ggplot2"))
```

## 

::: {style="font-size: 400%;text-align:center;"}
**Fragen?** 🤔
:::