project:
  type: website
  output-dir: docs

website:
  title: "Infos zum Workshop"
  navbar:
    left:
      - href: index.qmd
        text: Infos zum Workshop
      - href: quellen.qmd
        text: Weitere Quellen

format:
  html:
    theme: lux
    css: styles.css
    toc: false

