project:
  type: website
  output-dir: docs

website:
  title: "Digitale Datenspuren: Workshop"
  navbar:
    search: false
    pinned: true
    tools:
      - icon: twitter
        href: https://twitter.com/hase_va
      - icon: github
        href: https://github.com/valeriehase/data-donation

format:
  html:
    theme: lux
    css: styles.css
    toc: true

