project:
  type: website
  output-dir: docs

website:
  title: "Digitale Datenspuren: Workshop"
  navbar:
    left:
      - href: index.qmd
        text: Infos zum Workshop

format:
  html:
    theme: lux
    css: styles.css
    toc: true

